name: Build and Publish image to Docker Hub

on: workflow_dispatch


jobs:
  justcontainering:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: |
          docker build -t <imagenameisimportant> . 
#      - name: push image to docker hub
 #       run: |
  #        docker login -u rishabkumar7 -p ${{ secrets.DOCKER_HUB_TOKEN }}
   #       docker push rishabkumar7/devops-qr-code-backend:latest
    #      docker push rishabkumar7/devops-qr-code-frontend:latest
